URL=http://192.168.1.203/bankms/

!Execution Settings
Execution=local
Browser=chrome
gridurl=http://localhost:4444

emailaddress=vikram.joshi209@gmail.com
password=Vikram@852
emailaddresswithnoaccountopened=vikram.joshi309@gmail.com
passwordwithnoaccountopened=Vikram@852
aadharpath=C:\\Users\\Admin\\eclipse-workspace\\BankMS\\Sagar_Jadhav_BioData.pdf
pancardpath=C:\\Users\\Admin\\eclipse-workspace\\BankMS\\Sagar_Jadhav_BioData.pdf
unsupportedaadharpath=C:\\Users\\Admin\\eclipse-workspace\\BankMS\\New Text Document.exe
unsupportedpancardpath=C:\\Users\\Admin\\eclipse-workspace\\BankMS\\biodata.txt



!cashier login details
cashieremployeeid=MM57315
cashierpassword=Vikram@852
cashiermobilenumber=123
cashieremailaddress=vikram.joshi209@gmail.com
cashieroriginalpassword=Vikram@852
cashiernewchangedpassword=Sagar@19
cashierlonginputpassword=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl
cashieremployeeidwithminimuminputcharacter=E
cashierpasswordforempidwithminimuminputcharacter=Vikram@852
cashieremployeeidwithmaximuminputcharacter=EMP1234567890
cashierpasswordforempidwithmaximuminputcharacter=Vikram@852

cashierempidforminimumpasswordinputcharacter=EMP12345
cashierpasswordwithminimuminputcharacter=V
cashierempidformaximumpasswordinputcharacter=EMP67890
cashierpasswordwithmaximuminputcharacter=Vikram@852222
cashierempidwithspecialcharacterinemployeeidfield=EMP8318@.#
cashierempidwithspecialcharacterinpasswordfield=EMP8418
cashierpasswordwithspecialcharacterinemployeeidfield=Vikram@852
cashierpasswordwithspecialcharacterinpasswordfield=Vikram@852@.#*

!user account holder search data
accountholdername=Manish Gupta
accountholderpartialname=Manish
accountholdermobilenumber=1233211230
accountholderaccountnumber=147569176



